import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";   // ✅ Bootstrap CSS
// import "./globals.css";
import "../public/assets/scss/app.scss";

import Navbar from "./component/header/navbar";
import Footer from "./component/Footer/footer";
import AOSInitializer from "./component/AOSInitializer/AOSInitializer";
import BootstrapClient from "./component/BootstrapClient";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AOSInitializer />
        <BootstrapClient />
        <Navbar />
        {children}
        <Footer />


      </body>
    </html>
  );
}
